import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.awt.CardLayout;
import java.awt.Color;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author connollyl
 */
public class MenuScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuScreen
     */
    public MenuScreen() {
        initComponents();
    }
    private Order current = new Order();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        OrderLabel = new javax.swing.JLabel();
        FinishButton = new javax.swing.JButton();
        AdminControlPanelbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderList = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Hamburgerbutton = new javax.swing.JMenuItem();
        Baconburgerbutton = new javax.swing.JMenuItem();
        Cheeseburgerbutton = new javax.swing.JMenuItem();
        BCbutton = new javax.swing.JMenuItem();
        DoubleCbutton = new javax.swing.JMenuItem();
        Pizzaburgerbutton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Spaghettibutton = new javax.swing.JMenuItem();
        MnCbutton = new javax.swing.JMenuItem();
        Chickenbutton = new javax.swing.JMenuItem();
        PastaPbutton = new javax.swing.JMenuItem();
        BeefStroganbutton = new javax.swing.JMenuItem();
        Tetrabutton = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Chefsaladbutton = new javax.swing.JMenuItem();
        VBbutton = new javax.swing.JMenuItem();
        LSbutton = new javax.swing.JMenuItem();
        BCTbutton = new javax.swing.JMenuItem();
        CMRbutton = new javax.swing.JMenuItem();
        LMPbutton = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        HFbutton = new javax.swing.JMenuItem();
        SSbutton = new javax.swing.JMenuItem();
        CCbutton = new javax.swing.JMenuItem();
        MozzSticksbutton = new javax.swing.JMenuItem();
        OnionRbutton = new javax.swing.JMenuItem();
        PSbutton = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        APbutton = new javax.swing.JMenuItem();
        Cheesecakebutton = new javax.swing.JMenuItem();
        RVICSbutton = new javax.swing.JMenuItem();
        Sundaebutton = new javax.swing.JMenuItem();
        VanillCbutton = new javax.swing.JMenuItem();
        CICbutton = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        Waterbutton = new javax.swing.JMenuItem();
        Lemonadebutton = new javax.swing.JMenuItem();
        Milkbutton = new javax.swing.JMenuItem();
        AppleJbutton = new javax.swing.JMenuItem();
        OJbutton = new javax.swing.JMenuItem();
        IceTbutton = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAL™ Restaurant System");
        setPreferredSize(new java.awt.Dimension(1024, 576));

        OrderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderLabel.setText("Your Order");

        FinishButton.setText("Finish and Pay");
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        AdminControlPanelbutton.setText("Admin Panel");
        AdminControlPanelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminControlPanelbuttonActionPerformed(evt);
            }
        });

        OrderList.setEditable(false);
        OrderList.setColumns(20);
        OrderList.setRows(5);
        jScrollPane1.setViewportView(OrderList);

        jMenu1.setText("Burger Menu");
        jMenu1.setPreferredSize(new java.awt.Dimension(77, 27));

        Hamburgerbutton.setText("Hamburger");
        Hamburgerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HamburgerbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(Hamburgerbutton);

        Baconburgerbutton.setText("Baconburger");
        Baconburgerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaconburgerbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(Baconburgerbutton);

        Cheeseburgerbutton.setText("Cheeseburger");
        Cheeseburgerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseburgerbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(Cheeseburgerbutton);

        BCbutton.setText("Bacon Cheeseburger");
        BCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(BCbutton);

        DoubleCbutton.setText("Double Cheeseburger");
        DoubleCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleCbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(DoubleCbutton);

        Pizzaburgerbutton.setText("Pizzaburger");
        Pizzaburgerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaburgerbuttonActionPerformed(evt);
            }
        });
        jMenu1.add(Pizzaburgerbutton);

        jMenuBar1.add(jMenu1);

        jMenu2.setLabel("Pasta Menu");

        Spaghettibutton.setText("Spaghetti");
        Spaghettibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaghettibuttonActionPerformed(evt);
            }
        });
        jMenu2.add(Spaghettibutton);

        MnCbutton.setText("Mac and Cheese");
        MnCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCbuttonActionPerformed(evt);
            }
        });
        jMenu2.add(MnCbutton);

        Chickenbutton.setText("Chicken Alferdo");
        Chickenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenbuttonActionPerformed(evt);
            }
        });
        jMenu2.add(Chickenbutton);

        PastaPbutton.setText("Pasta Primavera");
        PastaPbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastaPbuttonActionPerformed(evt);
            }
        });
        jMenu2.add(PastaPbutton);

        BeefStroganbutton.setText("Beef Stroganoff");
        BeefStroganbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefStroganbuttonActionPerformed(evt);
            }
        });
        jMenu2.add(BeefStroganbutton);

        Tetrabutton.setText("Tetrazzini");
        Tetrabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TetrabuttonActionPerformed(evt);
            }
        });
        jMenu2.add(Tetrabutton);

        jMenuBar1.add(jMenu2);

        jMenu4.setLabel("Vegan Menu");

        Chefsaladbutton.setText("Chef Salad");
        Chefsaladbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChefsaladbuttonActionPerformed(evt);
            }
        });
        jMenu4.add(Chefsaladbutton);

        VBbutton.setText("Veggie Burger");
        VBbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VBbuttonActionPerformed(evt);
            }
        });
        jMenu4.add(VBbutton);

        LSbutton.setText("Lentil Soup");
        LSbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSbuttonActionPerformed(evt);
            }
        });
        jMenu4.add(LSbutton);

        BCTbutton.setText("Buffalo Califlower Tacos");
        BCTbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCTbuttonActionPerformed(evt);
            }
        });
        jMenu4.add(BCTbutton);

        CMRbutton.setText("Creamy Mushroom Risotto");
        CMRbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMRbuttonActionPerformed(evt);
            }
        });
        jMenu4.add(CMRbutton);

        LMPbutton.setText("Lo-Mein Primavera");
        LMPbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LMPbuttonActionPerformed(evt);
            }
        });
        jMenu4.add(LMPbutton);

        jMenuBar1.add(jMenu4);

        jMenu5.setLabel("Sides Menu");

        HFbutton.setText("House Fries");
        HFbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HFbuttonActionPerformed(evt);
            }
        });
        jMenu5.add(HFbutton);

        SSbutton.setText("Side Salad");
        SSbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSbuttonActionPerformed(evt);
            }
        });
        jMenu5.add(SSbutton);

        CCbutton.setText("Cheese Curds");
        CCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCbuttonActionPerformed(evt);
            }
        });
        jMenu5.add(CCbutton);

        MozzSticksbutton.setText("Mozzarella Sticks");
        MozzSticksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MozzSticksbuttonActionPerformed(evt);
            }
        });
        jMenu5.add(MozzSticksbutton);

        OnionRbutton.setText("Onion Rings");
        OnionRbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnionRbuttonActionPerformed(evt);
            }
        });
        jMenu5.add(OnionRbutton);

        PSbutton.setText("Potato Salad");
        PSbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSbuttonActionPerformed(evt);
            }
        });
        jMenu5.add(PSbutton);

        jMenuBar1.add(jMenu5);

        jMenu6.setLabel("Dessert Menu");

        APbutton.setText("Apple Pie");
        APbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APbuttonActionPerformed(evt);
            }
        });
        jMenu6.add(APbutton);

        Cheesecakebutton.setText("Cheesecake");
        Cheesecakebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheesecakebuttonActionPerformed(evt);
            }
        });
        jMenu6.add(Cheesecakebutton);

        RVICSbutton.setText("Red Velvet Ice Cream Sandwich");
        RVICSbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RVICSbuttonActionPerformed(evt);
            }
        });
        jMenu6.add(RVICSbutton);

        Sundaebutton.setText("Sundae");
        Sundaebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundaebuttonActionPerformed(evt);
            }
        });
        jMenu6.add(Sundaebutton);

        VanillCbutton.setText("Vanilla Cupcake");
        VanillCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanillCbuttonActionPerformed(evt);
            }
        });
        jMenu6.add(VanillCbutton);

        CICbutton.setText("Chocolate Ice Cream");
        CICbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CICbuttonActionPerformed(evt);
            }
        });
        jMenu6.add(CICbutton);

        jMenuBar1.add(jMenu6);

        jMenu7.setLabel("Drinks Menu");

        Waterbutton.setText("Water");
        Waterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaterbuttonActionPerformed(evt);
            }
        });
        jMenu7.add(Waterbutton);

        Lemonadebutton.setText("Lemonade");
        Lemonadebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LemonadebuttonActionPerformed(evt);
            }
        });
        jMenu7.add(Lemonadebutton);

        Milkbutton.setText("Malk");
        Milkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkbuttonActionPerformed(evt);
            }
        });
        jMenu7.add(Milkbutton);

        AppleJbutton.setText("Apple Juice");
        AppleJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleJbuttonActionPerformed(evt);
            }
        });
        jMenu7.add(AppleJbutton);

        OJbutton.setText("Orange Juice");
        OJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OJbuttonActionPerformed(evt);
            }
        });
        jMenu7.add(OJbutton);

        IceTbutton.setText("Iced Tea");
        IceTbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceTbuttonActionPerformed(evt);
            }
        });
        jMenu7.add(IceTbutton);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(FinishButton)
                        .addGap(178, 178, 178)
                        .addComponent(AdminControlPanelbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(OrderLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(OrderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminControlPanelbutton)
                    .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        OrderLabel.getAccessibleContext().setAccessibleName("OrderLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaconburgerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaconburgerbuttonActionPerformed
        Food Baconburger = new Food("Baconburger", 4.25f);
        current.addItem(Baconburger);
        OrderList.append(Baconburger.toString());
    }//GEN-LAST:event_BaconburgerbuttonActionPerformed

    private void CheeseburgerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeseburgerbuttonActionPerformed
        Food Cheeseburger = new Food("Cheeseburger", 3.75f);
        current.addItem(Cheeseburger);
        OrderList.append(Cheeseburger.toString());
    }//GEN-LAST:event_CheeseburgerbuttonActionPerformed

    private void BCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCbuttonActionPerformed
        Food BCburger = new Food("Bacon Cheeseburger", 4.50f);
        current.addItem(BCburger);
        OrderList.append(BCburger.toString());
    }//GEN-LAST:event_BCbuttonActionPerformed

    private void DoubleCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleCbuttonActionPerformed
        Food DoubleCburger = new Food("Double Cheeseburger", 5.50f);
        current.addItem(DoubleCburger);
        OrderList.append(DoubleCburger.toString());
    }//GEN-LAST:event_DoubleCbuttonActionPerformed

    private void PizzaburgerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaburgerbuttonActionPerformed
        Food Pizzaburger = new Food("Pizzaburger", 3.25f);
        current.addItem(Pizzaburger);
        OrderList.append(Pizzaburger.toString());
    }//GEN-LAST:event_PizzaburgerbuttonActionPerformed

    private void SpaghettibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaghettibuttonActionPerformed
        Food Spaghetti = new Food("Spaghetti", 3.75f);
        current.addItem(Spaghetti);
        OrderList.append(Spaghetti.toString());
    }//GEN-LAST:event_SpaghettibuttonActionPerformed

    private void MnCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCbuttonActionPerformed
        Food MnCheese = new Food("Mac and Cheese", 2.50f);
        current.addItem(MnCheese);
        OrderList.append(MnCheese.toString());
    }//GEN-LAST:event_MnCbuttonActionPerformed

    private void ChickenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenbuttonActionPerformed
        Food ChickenAlfredo = new Food("Chicken Alfredo", 4.25f);
        current.addItem(ChickenAlfredo);
        OrderList.append(ChickenAlfredo.toString());
    }//GEN-LAST:event_ChickenbuttonActionPerformed

    private void PastaPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastaPbuttonActionPerformed
        Food PastaP = new Food("Pasta Primavera", 5.00f);
        current.addItem(PastaP);
        OrderList.append(PastaP.toString());
    }//GEN-LAST:event_PastaPbuttonActionPerformed

    private void BeefStroganbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefStroganbuttonActionPerformed
        Food Stroganoff = new Food("Beef Stroganoff", 5.50f);
        current.addItem(Stroganoff);
        OrderList.append(Stroganoff.toString());
    }//GEN-LAST:event_BeefStroganbuttonActionPerformed

    private void TetrabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TetrabuttonActionPerformed
        Food Tetrazzini = new Food("Tetrazzini", 4.50f);
        current.addItem(Tetrazzini);
        OrderList.append(Tetrazzini.toString());
    }//GEN-LAST:event_TetrabuttonActionPerformed

    private void ChefsaladbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChefsaladbuttonActionPerformed
        Food ChefSalad = new Food("Chef Salad", 3.00f);
        current.addItem(ChefSalad);
        OrderList.append(ChefSalad.toString());
    }//GEN-LAST:event_ChefsaladbuttonActionPerformed

    private void VBbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VBbuttonActionPerformed
        Food VBurger = new Food("Veggie Burger", 5.50f);
        current.addItem(VBurger);
        OrderList.append(VBurger.toString());
    }//GEN-LAST:event_VBbuttonActionPerformed

    private void LSbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSbuttonActionPerformed
        Food LentilSoup = new Food("Lentil Soup", 3.00f);
        current.addItem(LentilSoup);
        OrderList.append(LentilSoup.toString());
    }//GEN-LAST:event_LSbuttonActionPerformed

    private void BCTbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCTbuttonActionPerformed
        Food BCT = new Food("Buffalo Cauliflower Tacos", 5.50f);
        current.addItem(BCT);
        OrderList.append(BCT.toString());
    }//GEN-LAST:event_BCTbuttonActionPerformed

    private void CMRbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMRbuttonActionPerformed
        Food CMR = new Food("Creamy Mushroom Risotto", 6.50f);
        current.addItem(CMR);
        OrderList.append(CMR.toString());
    }//GEN-LAST:event_CMRbuttonActionPerformed

    private void LMPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LMPbuttonActionPerformed
        Food LMPrimavera = new Food("Lo-mein Primavera", 5.50f);
        current.addItem(LMPrimavera);
        OrderList.append(LMPrimavera.toString());
    }//GEN-LAST:event_LMPbuttonActionPerformed

    private void HFbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HFbuttonActionPerformed
        Food HFries = new Food("House Fries", 1.50f);
        current.addItem(HFries);
        OrderList.append(HFries.toString());
    }//GEN-LAST:event_HFbuttonActionPerformed

    private void SSbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSbuttonActionPerformed
        Food SideSalad = new Food("Side Salad", 2.50f);
        current.addItem(SideSalad);
        OrderList.append(SideSalad.toString());
    }//GEN-LAST:event_SSbuttonActionPerformed

    private void CCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCbuttonActionPerformed
        Food CheeseCurds = new Food("Cheese Curds", 3.50f);
        current.addItem(CheeseCurds);
        OrderList.append(CheeseCurds.toString());
    }//GEN-LAST:event_CCbuttonActionPerformed

    private void MozzSticksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MozzSticksbuttonActionPerformed
        Food MozzSticks = new Food("Mozzarella Sticks", 3.50f);
        current.addItem(MozzSticks);
        OrderList.append(MozzSticks.toString());
    }//GEN-LAST:event_MozzSticksbuttonActionPerformed

    private void OnionRbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnionRbuttonActionPerformed
        Food ORings = new Food("Onion Rings", 3.50f);
        current.addItem(ORings);
        OrderList.append(ORings.toString());
    }//GEN-LAST:event_OnionRbuttonActionPerformed

    private void PSbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSbuttonActionPerformed
        Food PotatoSalad = new Food("Potato Salad", 3.50f);
        current.addItem(PotatoSalad);
        OrderList.append(PotatoSalad.toString());
    }//GEN-LAST:event_PSbuttonActionPerformed

    private void APbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APbuttonActionPerformed
        Food AppPie = new Food("Apple Pie", 3.50f);
        current.addItem(AppPie);
        OrderList.append(AppPie.toString());
    }//GEN-LAST:event_APbuttonActionPerformed

    private void CheesecakebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheesecakebuttonActionPerformed
        Food Cheesecake = new Food("Cheesecake", 3.50f);
        current.addItem(Cheesecake);
        OrderList.append(Cheesecake.toString());
    }//GEN-LAST:event_CheesecakebuttonActionPerformed

    private void RVICSbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RVICSbuttonActionPerformed
        Food RVICS = new Food("Red Velvet Ice Cream Sandwich", 3.50f);
        current.addItem(RVICS);
        OrderList.append(RVICS.toString());
    }//GEN-LAST:event_RVICSbuttonActionPerformed

    private void SundaebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundaebuttonActionPerformed
        Food Sundae = new Food("Sundae", 3.50f);
        current.addItem(Sundae);
        OrderList.append(Sundae.toString());
    }//GEN-LAST:event_SundaebuttonActionPerformed

    private void VanillCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanillCbuttonActionPerformed
        Food VCupcake = new Food("Vanilla Cupcake", 3.50f);
        current.addItem(VCupcake);
        OrderList.append(VCupcake.toString());
    }//GEN-LAST:event_VanillCbuttonActionPerformed

    private void CICbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CICbuttonActionPerformed
        Food ChocIce = new Food("Chocolate Ice Cream", 3.50f);
        current.addItem(ChocIce);
        OrderList.append(ChocIce.toString());
    }//GEN-LAST:event_CICbuttonActionPerformed

    private void LemonadebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LemonadebuttonActionPerformed
        Drink Lemonade = new Drink("Lemonade", 1.50f);
        current.addItem(Lemonade);
        OrderList.append(Lemonade.toString());
    }//GEN-LAST:event_LemonadebuttonActionPerformed

    private void MilkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkbuttonActionPerformed
        Drink Malk = new Drink("Malk", 2.00f);
        current.addItem(Malk);
        OrderList.append(Malk.toString());
    }//GEN-LAST:event_MilkbuttonActionPerformed

    private void AppleJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleJbuttonActionPerformed
        Drink ApJu = new Drink("Apple Juice", 1.00f);
        current.addItem(ApJu);
        OrderList.append(ApJu.toString());
    }//GEN-LAST:event_AppleJbuttonActionPerformed

    private void OJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OJbuttonActionPerformed
        Drink OrJu = new Drink("Orange Juice", 1.00f);
        current.addItem(OrJu);
        OrderList.append(OrJu.toString());
    }//GEN-LAST:event_OJbuttonActionPerformed

    private void IceTbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceTbuttonActionPerformed
        Drink IceT = new Drink("Iced Tea", 1.00f);
        current.addItem(IceT);
        OrderList.append(IceT.toString());
    }//GEN-LAST:event_IceTbuttonActionPerformed

    private void WaterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaterbuttonActionPerformed
        Drink Water = new Drink("Water", 1.00f);
        current.addItem(Water);
        OrderList.append(Water.toString());
    }//GEN-LAST:event_WaterbuttonActionPerformed

    private void HamburgerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HamburgerbuttonActionPerformed
        Food Hamburger = new Food("Hamburger", 3.50f);
        current.addItem(Hamburger);
        OrderList.append(Hamburger.toString());
    }//GEN-LAST:event_HamburgerbuttonActionPerformed

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        PaymentScreen pay = new PaymentScreen(OrderList);
        pay.setVisible(true);
        this.add(pay);
    }//GEN-LAST:event_FinishButtonActionPerformed

    private void AdminControlPanelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminControlPanelbuttonActionPerformed
        AdminPanel AP = new AdminPanel();
        AP.setVisible(true);
        this.add(AP);
    }//GEN-LAST:event_AdminControlPanelbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem APbutton;
    private javax.swing.JButton AdminControlPanelbutton;
    private javax.swing.JMenuItem AppleJbutton;
    private javax.swing.JMenuItem BCTbutton;
    private javax.swing.JMenuItem BCbutton;
    private javax.swing.JMenuItem Baconburgerbutton;
    private javax.swing.JMenuItem BeefStroganbutton;
    private javax.swing.JMenuItem CCbutton;
    private javax.swing.JMenuItem CICbutton;
    private javax.swing.JMenuItem CMRbutton;
    private javax.swing.JMenuItem Cheeseburgerbutton;
    private javax.swing.JMenuItem Cheesecakebutton;
    private javax.swing.JMenuItem Chefsaladbutton;
    private javax.swing.JMenuItem Chickenbutton;
    private javax.swing.JMenuItem DoubleCbutton;
    private javax.swing.JButton FinishButton;
    private javax.swing.JMenuItem HFbutton;
    private javax.swing.JMenuItem Hamburgerbutton;
    private javax.swing.JMenuItem IceTbutton;
    private javax.swing.JMenuItem LMPbutton;
    private javax.swing.JMenuItem LSbutton;
    private javax.swing.JMenuItem Lemonadebutton;
    private javax.swing.JMenuItem Milkbutton;
    private javax.swing.JMenuItem MnCbutton;
    private javax.swing.JMenuItem MozzSticksbutton;
    private javax.swing.JMenuItem OJbutton;
    private javax.swing.JMenuItem OnionRbutton;
    private javax.swing.JLabel OrderLabel;
    private javax.swing.JTextArea OrderList;
    private javax.swing.JMenuItem PSbutton;
    private javax.swing.JMenuItem PastaPbutton;
    private javax.swing.JMenuItem Pizzaburgerbutton;
    private javax.swing.JMenuItem RVICSbutton;
    private javax.swing.JMenuItem SSbutton;
    private javax.swing.JMenuItem Spaghettibutton;
    private javax.swing.JMenuItem Sundaebutton;
    private javax.swing.JMenuItem Tetrabutton;
    private javax.swing.JMenuItem VBbutton;
    private javax.swing.JMenuItem VanillCbutton;
    private javax.swing.JMenuItem Waterbutton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
